---
- name: Ensure virtual environment directory exists
  ansible.builtin.file:
    path: "{{ python_venv_path | dirname }}"
    state: directory
    owner: "{{ python_venv_owner }}"
    group: "{{ python_venv_group }}"
    mode: "{{ python_venv_mode }}"

- name: Create Python virtual environment
  ansible.builtin.command: "python3 -m venv {{ python_venv_path }}"
  args:
    creates: "{{ python_venv_path }}/bin/activate"

- name: Upgrade pip in virtual environment
  ansible.builtin.pip:
    name: pip
    state: "{{ python_venv_pip_version }}"
    virtualenv: "{{ python_venv_path }}"
    virtualenv_command: "python3 -m venv"

- name: Install pip packages in virtual environment
  ansible.builtin.pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    virtualenv: "{{ python_venv_path }}"
    virtualenv_command: "python3 -m venv"
  loop: "{{ python_venv_packages }}"
  when: python_venv_packages | length > 0

- name: Install packages from requirements file
  ansible.builtin.pip:
    requirements: "{{ python_requirements_file }}"
    virtualenv: "{{ python_venv_path }}"
    virtualenv_command: "python3 -m venv"
  when: python_requirements_file is defined
